### PR TITLE
#3 synchronizing subprojects

### PR DESCRIPTION
**Pull request by d-led**
platform doesn't build successfully yet, it seems unrelated to the commit, but since the [change to 0.7.5](
https://travis-ci.org/vlingo/vlingo-platform/builds/469289293).

Ready to be merged, as unrelated to the failure

### CODE REVIEW

**Comment by d-led** [comment]
```
[ERROR] .../src/vlingo/vlingo-actors/src/main/java/io/vlingo/actors/Actor.java:[14,24] cannot find symbol
  symbol:   class ResultCompletes
  location: package io.vlingo.common
[ERROR] .../src/vlingo/vlingo-actors/src/main/java/io/vlingo/actors/Actor.java:[18,9] cannot find symbol
  symbol:   class ResultCompletes
  location: class io.vlingo.actors.Actor
[ERROR] .../src/vlingo/vlingo-actors/src/main/java/io/vlingo/actors/Actor.java:[87,26] cannot find symbol
  symbol:   class ResultCompletes
  location: class io.vlingo.actors.Actor
[ERROR] .../src/vlingo/vlingo-actors/src/main/java/io/vlingo/actors/LocalMessage.java:[110,12] illegal start of type
```

**Comment by VaughnVernon** [comment]
@d-led This build problem may be due to an example that was left stray (because it doesn't auto checkout): `vlingo-eventjournal`

The `vlingo-actors` built fine on Sunday with the `0.7.5` release. Perhaps this build error is environmental. Thoughts?

Hmmm, actually `ResultCompletes` was moved from `vlingo-common` back to `vlingo-actors`. It looks like you don't have all of `0.7.5` on your local build.

**Review by VaughnVernon — APPROVED** [review]
Awesome, thanks @d-led !

**Comment by d-led** [comment]
@VaughnVernon on the local build failure, I will throw away the repos and checkout anew
As for travis-ci we need to find a way to minimize the build verbosity. Travis-CI aborts the build with the [message](https://api.travis-ci.org/v3/job/469694242/log.txt): 

```
The job exceeded the maximum log length, and has been terminated.
```

**Comment by VaughnVernon** [comment]
@d-led Yeah, it doesn't abort. It just stops outputting log entries. But for sure we need to reduce the test output. I am not sure where this came from all of the sudden. @DaveMuirhead mentioned that his `Router` support tests may be adding some verbosity. (Umm, at least the other day it didn't abort the build. Maybe the behavior has changed.)

**Comment by d-led** [comment]
it seems, a large chunk is coming from `maven-javadoc-plugin:3.0.0:jar (attach-javadocs) @ vlingo-actors ---`

**Comment by d-led** [comment]
builds fine locally now

**Comment by VaughnVernon** [comment]
@d-led Yes, a lot is from the Javadoc creation and I also have some `intended failure` tests that are used for confirming supervision behavior and these cause a lot of exception stack trace output. However, both of those sections have been generating output for a long time. Whatever is overflowing the logs is new.

**Comment by d-led** [comment]
i've added the `-B` (batch) flag to the travis config in this repo. This lets the build finish

**Pull request merged**
